### PR TITLE
Update database references to drop the year.

### PR DESCRIPTION
**Pull request by Eleeleth**
Fixes pyohio/pyohio#34 by updating references to the pyohio2014 database to pyohio.

### CODE REVIEW

**Comment by efloehr** [comment]
Hi Eleeleth! Thanks so much for the pull request. Previously, we hand-copied the old data to the new database every year, and it's been a pain. There is a way to use the same database every year and that's what I want to get to with this code. Can I ask you instead to submit a pull request with the database named "pyohio" instead of with a named year? Thanks again!

**Comment by Eleeleth** [comment]
Sure, I can do that later today!

**Comment by Eleeleth** [comment]
@efloehr I've updated the pull request with your requested changes.

**Comment by efloehr** [comment]
Thanks so much!

**Pull request merged**
