### PR TITLE
Add twit and rewviewr fields to api.

### PR DESCRIPTION
**Pull request by CarlFK**

### CODE REVIEW

**Comment by efloehr** [comment]
This is covered in #66

**Comment by chrisjrn** [comment]
Time to re-open -- these changes, for some reason, are not reflected in `master`.

**Comment by chrisjrn** [comment]
And a quick visual check says that this is correct. OK to merge.

**Comment by efloehr** [comment]
Chris, it's because #66 is on the pyohio2017 branch, which is what we've frozen for this year. Master is for future, and we'll migrate pyohio2017 to it at some point.

**Pull request closed without merging**
